### PR TITLE
Add CAN transport

### PR DESCRIPTION
**Pull request by Acuadros95**

### CODE REVIEW

**Review by pablogs9 — APPROVED** [review]
Clock configuration is not required to be changed at the end?

**Comment by pablogs9** [comment]
@mergify backport foxy main

**Comment by Acuadros95** [comment]
> Clock configuration is not required to be changed at the end?

Yes, will modify it in next commits

**Review by pablogs9 — APPROVED** [review]

**Comment by Acuadros95** [comment]
@mergify backport main foxy

**Pull request merged**
